### ISSUE TITLE
Kubenetes集群管理添加了k8s的config内容，但查不到命名空间

### ISSUE THREAD

**Issue by huanzui** [ixrjog/opscloud#30]
请问下 Kubenetes集群管理添加了k8s的config内容，但查不到命名空间，这还需要填什么么？

**Comment by ixrjog** [comment]
1. 配置文件
application-kubernetes-open.yml
此配置文件可以配置过滤掉没用的命名空间和 deployment/service命名规则（前缀&后缀）
2. 配置完集群后可以按命名空间同步deployment/service
```
# kubeconfig path = ${dataPath}/kubeconfig
# namespace.filter 命名空间过滤
# deployment.nomenclature
# 无状态命名规范 配置为空会省略链接符号-
# ${deployment.nomenclature.prefix}-${applicationInstanceName}-${envLabel}-${deployment.nomenclature.suffix}
# service.nomenclature
# 服务命名规范 配置为空会省略链接符号-
# ${service.nomenclature.prefix}-${applicationInstanceName}-${envLabel}-${service.nomenclature.suffix}

kubernetes:
  version: 0.0.0
  dataPath: /data/opscloud-data/kubernetes
  namespace:
    filter:
      - default
      - kube-node-lease
      - kube-public
      - kube-system
      - upgrade-ns-logtail-ds
  application:
    envLabel:
      test:
        - dev
        - daily
      pre:
        - pre
  deployment:
    nomenclature:
      prefix:
      suffix: 'deployment'
  service:
    nomenclature:
      prefix:
      suffix: 'lb'
```
